In [1]:
import pandas as pd
import os
from pathlib import Path
import matplotlib.pyplot as plt
import datetime

read_path = r'C:\Users\Julia\Documents\Uni\Master\1\Data-Literacy\Daten\joined_survey_article_standardized_median.csv'
df = pd.read_csv(read_path, delimiter=';', header=0)
df["date"] = pd.to_datetime(df["date"], format="%d.%m.%Y")
df["SPD"] = pd.to_numeric(df["SPD"], errors='coerce')
df["Union"] = pd.to_numeric(df["Union"], errors='coerce')
df["Grüne"] = pd.to_numeric(df["Grüne"], errors='coerce')
df["FDP"] = pd.to_numeric(df["FDP"], errors='coerce')
df["AfD"] = pd.to_numeric(df["AfD"], errors='coerce')
df["Linke"] = pd.to_numeric(df["Linke"], errors='coerce')

In [2]:
df

,Unnamed: 0,date,SPD,Union,Grüne,FDP,AfD,Linke,FW,Andere,standardized_war_articles
0,0,2023-12-22,14.0,32.0,14.0,5.0,21.0,3.0,4,7,0.149730
1,1,2023-12-07,14.0,32.0,15.0,4.0,21.0,3.0,3,8,0.169740
2,2,2023-11-10,15.0,30.0,15.0,5.0,21.0,4.0,3,7,0.193503
3,3,2023-11-02,16.0,30.0,14.0,4.0,22.0,5.0,3,6,0.179060
4,4,2023-10-13,15.0,29.0,13.0,5.0,23.0,4.0,4,7,0.195236
...,...,...,...,...,...,...,...,...,...,...,...
685,685,2000-07-01,39.0,38.0,6.0,8.0,NaN,5.0,-,4,0.008333
686,686,2000-06-01,38.0,39.0,7.0,9.0,NaN,5.0,-,2,0.015557
687,687,2000-05-01,41.0,36.0,6.0,7.0,NaN,5.0,-,5,0.027951
688,688,2000-04-07,39.0,34.0,8.0,7.0,NaN,7.0,-,5,0.014863
689,689,2000-03-03,42.0,31.0,7.0,9.0,NaN,7.0,-,4,0.000000

In [4]:
correlation_matrix = df.corr()

correlation_matrix

C:\Users\Julia\AppData\Local\Temp\ipykernel_13848\2833026755.py:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = df.corr()

,Unnamed: 0,SPD,Union,Grüne,FDP,AfD,Linke,standardized_war_articles
Unnamed: 0,1.000000,0.790215,0.704783,-0.613996,0.106899,-0.744787,-0.209843,-0.128824
SPD,0.790215,1.000000,0.445705,-0.670112,-0.019615,-0.653440,-0.155073,-0.102354
Union,0.704783,0.445705,1.000000,-0.587615,-0.308989,-0.731224,-0.264622,-0.004192
Grüne,-0.613996,-0.670112,-0.587615,1.000000,-0.122157,0.357925,-0.028808,0.067167
FDP,0.106899,-0.019615,-0.308989,-0.122157,1.000000,0.436607,0.317068,-0.150001
AfD,-0.744787,-0.653440,-0.731224,0.357925,0.436607,1.000000,-0.329152,0.156412
Linke,-0.209843,-0.155073,-0.264622,-0.028808,0.317068,-0.329152,1.000000,-0.293275
standardized_war_articles,-0.128824,-0.102354,-0.004192,0.067167,-0.150001,0.156412,-0.293275,1.000000